// <auto-generated />
using System;
using Menu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Menu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527095229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Menu.Models.ConfiguracionMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioMenu")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionMenu", (string)null);
                });

            modelBuilder.Entity("Menu.Models.ConsumoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConsumoMenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoCobro")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormaCobro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioRegistroNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsumoMenuId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("ConsumosAdicionales", (string)null);
                });

            modelBuilder.Entity("Menu.Models.ConsumoMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioMenu")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPagoMenu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioRegistroNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("Fecha", "EmpleadoId", "TipoServicio")
                        .IsUnique();

                    b.ToTable("ConsumosMenu", (string)null);
                });

            modelBuilder.Entity("Menu.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("Menu.Models.PagoConsumoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormaPago")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioRegistroNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("PagosConsumosAdicionales", (string)null);
                });

            modelBuilder.Entity("Menu.Models.PagoConsumoAdicionalDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumoAdicionalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PagoConsumoAdicionalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsumoAdicionalId");

                    b.HasIndex("PagoConsumoAdicionalId");

                    b.ToTable("PagosConsumosAdicionalesDetalle", (string)null);
                });

            modelBuilder.Entity("Menu.Models.PermisoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PermisosSistema", (string)null);
                });

            modelBuilder.Entity("Menu.Models.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermisoSistemaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolSistemaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PermisoSistemaId");

                    b.HasIndex("RolSistemaId", "PermisoSistemaId")
                        .IsUnique();

                    b.ToTable("RolesPermisos", (string)null);
                });

            modelBuilder.Entity("Menu.Models.RolSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("RolesSistema", (string)null);
                });

            modelBuilder.Entity("Menu.Models.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RolSistemaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolSistemaId");

                    b.ToTable("UsuariosSistema", (string)null);
                });

            modelBuilder.Entity("Menu.Models.ConsumoAdicional", b =>
                {
                    b.HasOne("Menu.Models.ConsumoMenu", "ConsumoMenu")
                        .WithMany("ConsumosAdicionales")
                        .HasForeignKey("ConsumoMenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Menu.Models.Empleado", "Empleado")
                        .WithMany("ConsumosAdicionales")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsumoMenu");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Menu.Models.ConsumoMenu", b =>
                {
                    b.HasOne("Menu.Models.Empleado", "Empleado")
                        .WithMany("ConsumosMenu")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Menu.Models.PagoConsumoAdicional", b =>
                {
                    b.HasOne("Menu.Models.Empleado", "Empleado")
                        .WithMany("PagosAdicionales")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Menu.Models.PagoConsumoAdicionalDetalle", b =>
                {
                    b.HasOne("Menu.Models.ConsumoAdicional", "ConsumoAdicional")
                        .WithMany("PagoDetalles")
                        .HasForeignKey("ConsumoAdicionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Menu.Models.PagoConsumoAdicional", "PagoConsumoAdicional")
                        .WithMany("Detalles")
                        .HasForeignKey("PagoConsumoAdicionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumoAdicional");

                    b.Navigation("PagoConsumoAdicional");
                });

            modelBuilder.Entity("Menu.Models.RolPermiso", b =>
                {
                    b.HasOne("Menu.Models.PermisoSistema", "PermisoSistema")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menu.Models.RolSistema", "RolSistema")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermisoSistema");

                    b.Navigation("RolSistema");
                });

            modelBuilder.Entity("Menu.Models.UsuarioSistema", b =>
                {
                    b.HasOne("Menu.Models.RolSistema", "RolSistema")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolSistemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolSistema");
                });

            modelBuilder.Entity("Menu.Models.ConsumoAdicional", b =>
                {
                    b.Navigation("PagoDetalles");
                });

            modelBuilder.Entity("Menu.Models.ConsumoMenu", b =>
                {
                    b.Navigation("ConsumosAdicionales");
                });

            modelBuilder.Entity("Menu.Models.Empleado", b =>
                {
                    b.Navigation("ConsumosAdicionales");

                    b.Navigation("ConsumosMenu");

                    b.Navigation("PagosAdicionales");
                });

            modelBuilder.Entity("Menu.Models.PagoConsumoAdicional", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Menu.Models.PermisoSistema", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Menu.Models.RolSistema", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
