// <auto-generated />
using System;
using Menu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Menu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615025640_AsociarComensalesEmpresaSucursal")]
    partial class AsociarComensalesEmpresaSucursal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Menu.Models.CierreProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaConfirmacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalExcluidoRevision")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalLiquidarProveedor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMenusActivos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMenusPlanilla")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMenusPlanillaExcluidos")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPersonalActivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPlanilla")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioConfirmacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioConfirmacionNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaDesde", "FechaHasta")
                        .IsUnique();

                    b.ToTable("CierresProveedor", (string)null);
                });

            modelBuilder.Entity("Menu.Models.CierreProveedorDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CierreProveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConsumoAdicionalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumoMenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmpleadoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExcluidoPorPagoDirecto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncluidoProveedor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoExclusion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipoAdicional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoPagoMenu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CierreProveedorId");

                    b.HasIndex("ConsumoAdicionalId");

                    b.HasIndex("ConsumoMenuId");

                    b.ToTable("CierresProveedorDetalle", (string)null);
                });

            modelBuilder.Entity("Menu.Models.ConfiguracionMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioMenu")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionMenu", (string)null);
                });

            modelBuilder.Entity("Menu.Models.ConsumoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConsumoMenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoCobro")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormaCobro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MotivoAnulacionConsumo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacionAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoAdicional")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioAnulacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioAnulacionNombre")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioRegistroNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsumoMenuId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("ConsumosAdicionales", (string)null);
                });

            modelBuilder.Entity("Menu.Models.ConsumoMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstadoCobroMenu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPagoMenu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormaPagoDirecto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacionAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioMenu")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipoMotivoAnulacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoPagoMenu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioAnulacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioAnulacionNombre")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioRegistroNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("Fecha", "EmpleadoId", "TipoServicio")
                        .IsUnique()
                        .HasFilter("\"Anulado\" = 0");

                    b.ToTable("ConsumosMenu", (string)null);
                });

            modelBuilder.Entity("Menu.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmpresaClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TipoEmpleadoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("EmpresaClienteId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("TipoEmpleadoId");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("Menu.Models.EmpresaCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreComercial")
                        .IsUnique();

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.ToTable("EmpresasCliente", (string)null);
                });

            modelBuilder.Entity("Menu.Models.PagoConsumoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormaPago")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioRegistroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioRegistroNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("PagosConsumosAdicionales", (string)null);
                });

            modelBuilder.Entity("Menu.Models.PagoConsumoAdicionalDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumoAdicionalId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PagoConsumoAdicionalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsumoAdicionalId");

                    b.HasIndex("PagoConsumoAdicionalId");

                    b.ToTable("PagosConsumosAdicionalesDetalle", (string)null);
                });

            modelBuilder.Entity("Menu.Models.PermisoSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PermisosSistema", (string)null);
                });

            modelBuilder.Entity("Menu.Models.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermisoSistemaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolSistemaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PermisoSistemaId");

                    b.HasIndex("RolSistemaId", "PermisoSistemaId")
                        .IsUnique();

                    b.ToTable("RolesPermisos", (string)null);
                });

            modelBuilder.Entity("Menu.Models.RolSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("RolesSistema", (string)null);
                });

            modelBuilder.Entity("Menu.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmpresaClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaClienteId");

                    b.HasIndex("Nombre", "EmpresaClienteId")
                        .IsUnique();

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("Menu.Models.TipoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposEmpleado", (string)null);
                });

            modelBuilder.Entity("Menu.Models.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RolSistemaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolSistemaId");

                    b.ToTable("UsuariosSistema", (string)null);
                });

            modelBuilder.Entity("Menu.Models.CierreProveedorDetalle", b =>
                {
                    b.HasOne("Menu.Models.CierreProveedor", "CierreProveedor")
                        .WithMany("Detalles")
                        .HasForeignKey("CierreProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CierreProveedor");
                });

            modelBuilder.Entity("Menu.Models.ConsumoAdicional", b =>
                {
                    b.HasOne("Menu.Models.ConsumoMenu", "ConsumoMenu")
                        .WithMany("ConsumosAdicionales")
                        .HasForeignKey("ConsumoMenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Menu.Models.Empleado", "Empleado")
                        .WithMany("ConsumosAdicionales")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsumoMenu");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Menu.Models.ConsumoMenu", b =>
                {
                    b.HasOne("Menu.Models.Empleado", "Empleado")
                        .WithMany("ConsumosMenu")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Menu.Models.Empleado", b =>
                {
                    b.HasOne("Menu.Models.EmpresaCliente", "EmpresaCliente")
                        .WithMany("Empleados")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Menu.Models.Sucursal", "Sucursal")
                        .WithMany("Empleados")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Menu.Models.TipoEmpleado", "TipoEmpleado")
                        .WithMany("Empleados")
                        .HasForeignKey("TipoEmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmpresaCliente");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoEmpleado");
                });

            modelBuilder.Entity("Menu.Models.PagoConsumoAdicional", b =>
                {
                    b.HasOne("Menu.Models.Empleado", "Empleado")
                        .WithMany("PagosAdicionales")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Menu.Models.PagoConsumoAdicionalDetalle", b =>
                {
                    b.HasOne("Menu.Models.ConsumoAdicional", "ConsumoAdicional")
                        .WithMany("PagoDetalles")
                        .HasForeignKey("ConsumoAdicionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Menu.Models.PagoConsumoAdicional", "PagoConsumoAdicional")
                        .WithMany("Detalles")
                        .HasForeignKey("PagoConsumoAdicionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumoAdicional");

                    b.Navigation("PagoConsumoAdicional");
                });

            modelBuilder.Entity("Menu.Models.RolPermiso", b =>
                {
                    b.HasOne("Menu.Models.PermisoSistema", "PermisoSistema")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menu.Models.RolSistema", "RolSistema")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermisoSistema");

                    b.Navigation("RolSistema");
                });

            modelBuilder.Entity("Menu.Models.Sucursal", b =>
                {
                    b.HasOne("Menu.Models.EmpresaCliente", "EmpresaCliente")
                        .WithMany("Sucursales")
                        .HasForeignKey("EmpresaClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmpresaCliente");
                });

            modelBuilder.Entity("Menu.Models.UsuarioSistema", b =>
                {
                    b.HasOne("Menu.Models.RolSistema", "RolSistema")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolSistemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolSistema");
                });

            modelBuilder.Entity("Menu.Models.CierreProveedor", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Menu.Models.ConsumoAdicional", b =>
                {
                    b.Navigation("PagoDetalles");
                });

            modelBuilder.Entity("Menu.Models.ConsumoMenu", b =>
                {
                    b.Navigation("ConsumosAdicionales");
                });

            modelBuilder.Entity("Menu.Models.Empleado", b =>
                {
                    b.Navigation("ConsumosAdicionales");

                    b.Navigation("ConsumosMenu");

                    b.Navigation("PagosAdicionales");
                });

            modelBuilder.Entity("Menu.Models.EmpresaCliente", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("Menu.Models.PagoConsumoAdicional", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Menu.Models.PermisoSistema", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Menu.Models.RolSistema", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Menu.Models.Sucursal", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Menu.Models.TipoEmpleado", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
